### ISSUE TITLE
Update Sorkin Type's Fonts (summary)

### ISSUE THREAD

**Issue by davelab6** [google/fonts#107]
Many of the type designers who have developed Latin font families have continued to work on them, and reviewing their collections and bringing them up to date would be good. 

#### Done
- [x] Alata / Last release: #2207
- [x] Spline Sans / Last release: #4502
- [x] #4646
- [x] #4648
- [x] #4647
- [x] #4676
- [x] #4616
- [x] #4692
- [x] #4664
- [x] #5940

#### In progress / planned
- [ ] Merriweather: #2943 #2632 https://github.com/SorkinType/Merriweather/issues/547

#### To plan / blocked
- [ ] #4665: [repo cleaned](https://github.com/SorkinType/Dekko/pull/7) but needs upstream work
- [ ] #1213: upstream is working on it
- [ ] #3826: upstream is working on it
- [ ] Limelight: no repo
- [ ] Gravitas One: no repo
- [ ] Inder: no repo
- [ ] Goblin One: no repo
- [ ] Autour One: no repo
- [ ] Plaster: no repo

**Comment by adrientetar** [comment]
So you found time to update existing families after all?

**Comment by davelab6** [comment]
https://github.com/weiweihuanghuang/Work-Sans/releases/tag/v1.51

**Comment by omerziv** [comment]
Hey @davelab6 - I think you should close this issue and split it up to specific issues for the fonts that actually need updates.

**Comment by laerm0** [comment]
I agree with @omerziv. What do you think, @davelab6? Can we close this?

**Comment by davelab6** [comment]
I'll keep this around in my project board as there's work to do here mining the far reaches of GitHub for individual issues 🤣

**Comment by RosaWagner** [comment]
@EbenSorkin can you give us some insights about the fonts listed in first comment; which one need to be upgraded and which one don't?

**Comment by EbenSorkin** [comment]
omission to the note above - Gelasio has Italics!

**Comment by EbenSorkin** [comment]
Merriweather - Some changes that are the new Merriweather should be applied to the 'standard' Merriweather which the new Merriweather incorporated as the smallest opsz. A few of these are Latin script specific. There are a large number of these that are Cyrillic script specific. Revised kerning should also be adopted. Merriweather could have Greek script support added. CERN has asked for that. Like Gelasio it could be made to support the global glyph list for Africa, Asia, and South America.

**Comment by EbenSorkin** [comment]
Alatsi - 

This is just one weight/style but it has the start of the Global glyph support with Pan African Latin having been added. I added that support for fun and because I think doing it is important. I also wanted to see how hard it really was to support Pan African Latin. It is a space-efficient semi condensed geometric sans design. It is somewhat lighter-hearted than some in the genre as well. It lacks small numbers. I think it could be popular with weights and Italics. It looks like this: 

<img width="620" alt="image" src="https://user-images.githubusercontent.com/2181213/160949882-6143a9ae-15c5-49a4-82a6-84bb23bd2c0d.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/2181213/160949959-e21222c8-2bfc-4f83-8917-c59b64d8d413.png">

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/2181213/160950167-780e94ae-9199-49c9-9f3d-339c6186ee07.png">

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/2181213/160950441-b4c7ee72-3241-47b7-8f17-f2d81a56f841.png">

<img width="1587" alt="image" src="https://user-images.githubusercontent.com/2181213/160950516-580bae49-8af1-4558-99f2-f96c4b4df6a7.png">

<img width="2290" alt="image" src="https://user-images.githubusercontent.com/2181213/160951035-28d3a024-b27f-40da-8477-0e9ed6da038a.png">

It was originally made around the time of Merriweather - so pre- retina screens so it goes to small sizes very  well. It some ways this might be a good one to bring an Opsz to. Here is small size text example:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/2181213/160951317-4a1d575c-35d3-461d-9bba-d3344a005b46.png">

**Comment by RosaWagner** [comment]
Thanks @EbenSorkin, for now we only need to know which font has a new version already available (compare to what GF serves atm), and what has been upgraded in those version. Mixing this with ideas of improvement is a bit confusing for me, i am afraid I gonna have everything mixed up. For the new ideas I suggest to make a separate list and submit it in another issue ;)

can you do a synthetic list following this scheme?
* font name - new version number - upgrade (italic added, bug fixes, expand glyphset to African languages etc)

**Comment by EbenSorkin** [comment]
Yes, I can build that. Thanks for the clarification!

**Comment by davelab6** [comment]
@EbenSorkin per https://github.com/SorkinType/Merriweather/issues/547 what should the new opsz'd MW family name be? Merriweather Flex? :)

**Comment by EbenSorkin** [comment]
I am happy with that if the standard for bearing the name Flex is that it
has opsz and wdth I guess. Is it?

-e.

**Comment by davelab6** [comment]
@EbenSorkin it is

**Comment by EbenSorkin** [comment]
Great

**Comment by chrissimpkins** [comment]
Closing.  Let's spin up separate per family issue tracker threads for any outstanding work here.
