### ISSUE TITLE
Update Big Shoulders families to 'wght' VF

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#3433]
Giving continuity to [#2426](https://github.com/google/fonts/issues/2426#issuecomment-629001524) 

> Step 3. Update with Weight axes
> Update Big Shoulders Text Stencil, Big Shoulders Display Stencil, Big Shoulders Text Inline and Big Shoulders Display Inline families with variable fonts containing a wght axis, that 1:1 matches the prior static releases.

- [x] Big Shoulders Text #3432 
- [x] Big Shoulders Display #3434 
- [x] Big Shoulders Stencil Text #3435
- [x] Big Shoulders Stencil Display #3436
- [x] Big Shoulders Inline Text #3437
- [x] Big Shoulders Inline Display #3438
