### ISSUE TITLE
Add description to Khmer fonts

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#3674]
- [x] 1. Angkor is a Khmer font for headlines and even banner designs. #3505 

- [x] 2. Battambang is a Khmer font for body text. The shape is similar to the Battambang legacy font released in the 1990s. #3491 

- [x] 3. Hanuman is a Khmer font for body text, that pairs well with Latin serif fonts. #3496 

- [x] 4. Nokora is a Khmer font for body text, that pairs well with Latin sans serif fonts. #3499

- [x] 6. Moul is a traditional Khmer typeface design, suitable for headlines, titles, subtitles, and even banner designs. #3509 

- [x] 7. Koulen is a Khmer font for headlines, titles and subtitles, and even banner designs. #3511 

- [x] 8. Metal is a Khmer font with a design similar to the Khmer Italic metal types published in Cambodia before 1970. #3501 

- [x] 9. Bokor is a display Khmer font, suitable for headlines, titles, subtitles, and even banner designs. #3508 

- [x] 11. Bayon is a Khmer font for headlines, titles and subtitles, and even banner designs. #3498 

- [x] 12. Odor Mean Chey is a Khmer font for headlines, titles and subtitles, and even banner designs. #3500 

- [x] 14. Dangrek is a Khmer font for headlines, titles and subtitles, and even banner designs. #3507 

- [x] 15. Freehand is a Khmer font for body text. The design is inspired by a popular style of Khmer handwriting letterforms. #3510 

- [x] 16. Taprom is a Khmer font for body text. The design is inspired by a popular style of Khmer handwriting letterforms. #3504 

- [x] 18. Preahvihear is a Khmer font for headlines, titles and subtitles, and even banner designs. #3503 

- [x] 19. Suwannaphum is a Khmer font for body text, that pairs well with Latin serif fonts. #3495 

- [x] 20. Moulpali is a typeface for Khmer body text, the design is similar to some Khmer metal types popular in the 1960s. #3502 

- [x] 21. Fasthand is a Khmer font for body text. The design is inspired by a popular style of Khmer handwriting letterforms that are written quickly. #3512 

- [x] 22. Koh Santepheap is a Khmer font for body text, that pairs well with Latin serif fonts and for bilingual (English - Khmer) text. #3506

**Not in this batch:**
- Chenla is a typeface for Khmer body text, the design is similar to some Khmer metal types popular in the 1960s. #3790
- Content is a Khmer font for body text, with a design inspired by the Limon S1 legacy font, released in the 1990s.  #3201 
- Khmer is a new typeface for Khmer body text, the design is similar to some Khmer metal types popular in the 1980s. #3199 
- Siemreap is a typeface for Khmer body text, the design is similar to some Khmer metal types popular in the 1960s. #3197
