### ISSUE TITLE
Add Kantumruy Pro

### ISSUE THREAD

**Issue by sovichet** [google/fonts#4604]
**Font Project Git Repo URL:**
https://github.com/sovichet/kantumruy-pro

**Super short description of the Font Family:**
Kantumruy Pro is a newly redrawn design of the first Kantumruy (published in 2013).

![02-KantumruyPro_Promo](https://user-images.githubusercontent.com/1669566/167113977-f90a17da-c504-4c0b-8235-79346a11e186.png)

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Todo:**

- [ ] Remove Kantumruy from the platform

**Comment by sovichet** [comment]
@RosaWagner I've just found some bugs and a few points that I missed during the production. I'll get them fixed within next week and will post an update issue.
