### ISSUE TITLE
Add Kdam Thmor Pro

### ISSUE THREAD

**Issue by sovichet** [google/fonts#4605]
**Font Project Git Repo URL:**
https://github.com/sovichet/kdam-thmor-pro

**Super short description of the Font Family:**
Kdam Thmor Pro is a revised design of "Kdam Thmor" which is one of Sovichet Tep's typefaces designed and published back in 2013 on Google Fonts.

![image1](https://user-images.githubusercontent.com/1669566/167115218-83674d25-158f-427e-84d7-d2d119810935.png)

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Todo:**

- [ ] Add Hak Longdey's bio
- [ ] Remove the current Kdam Thmor from the platform

**Comment by sovichet** [comment]
@RosaWagner when should we remove the old version from the platform?

CC @davelab6
