### ISSUE TITLE
Zacbel X

### ISSUE THREAD

**Issue by zacbel** [google/fonts#4771]
**Font Project Git Repo URL:**
https://drive.google.com/file/d/1opzBmUzQJ62YQRjhUwfJaP-ayckNiora/view?usp=sharing

**Super short description of the Font Family:**
A new, modern sans serif that fits perfectly in any environment.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**
![zbximage](https://user-images.githubusercontent.com/105535304/173192298-40f0dbdc-945a-4f1e-9bbf-367509fab7e5.png)

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi, thanks for your submission. I un-ticked the requirements which were not fulfilled. Please read them carefully and feel free to re-open this issue once the project matches them all :)
