### ISSUE TITLE
Add A Love of Thunder

### ISSUE THREAD

**Issue by yesprit-trinity** [google/fonts#5146]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://github.com/google/fonts/blob/main/CONTRIBUTING.md)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

![image](https://user-images.githubusercontent.com/90280633/187286431-f9d97978-3c29-4482-a8a1-49ffa009a8f0.png)

**Comment by inferno986return** [comment]
I did manage to find this font and it's by another developer: https://rolltop-indigo.blogspot.com/p/the-cumberland-fontworks.html

A Love of Thunder wouldn't be able to be added unless the developer S. John Ross creates a GitHub repository for the font and releases it under OFL. You can contact them via e-mail.

**Comment by inferno986return** [comment]
I did e-mail the creator of this font and it will remain as proprietary software.
![Uploading Screenshot 2022-09-14 164858-redacted.png…]()
