### ISSUE TITLE
Families to de-list

### ISSUE THREAD

**Issue by RosaWagner** [google/fonts#5406]
**Families**
- [x] Fredoka One (expanded, now "Fredoka") (missing designer added in #5942)
- [x] Kantumruy (expanded, now "Kantumruy Pro")
- [x] Gentium Book Basic (expanded, now "Gentium Book Plus")
- [x] Arima Madurai (expanded, now "Arima")
- [x] Merienda One (expanded, now "Merienda")
- [x] #5689 (expanded, now "Coda")

**To de-list once families in prod**
- [x] N Ko (replaced by NKo) explained in #5608 
- [x] Noto Serif Nyiakeng Puachue Hmong (replaced by NP Hmong) explained in #5609 

**To do when done**
- [ ] Update TRIVIA.md
- [ ] Remove directories

**Comment by chrissimpkins** [comment]
Updated Merenda family name to Merienda.

**Comment by chrissimpkins** [comment]
The delisting request is filed with the Engineering team.
