### ISSUE TITLE
Add Someplace Yellow

### ISSUE THREAD

**Issue by gscotland** [google/fonts#5435]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**
<img width="102" alt="Screen Shot 2022-10-19 at 1 59 09 PM" src="https://user-images.githubusercontent.com/116200311/196768992-810120ab-c9e5-478d-93bf-dd177b854c87.png">

Attach here a pic or a screenshot of the font; one is enough, it can be few letters, to give a quick overview.

**Comment by RosaWagner** [comment]
Hi, thanks for your submission. It looks like there is no font, therefore we can't onboard it. We will be happy to re-open this submission as soon as there is more material to review, and actual compliance to the listed requirements above.
