### ISSUE TITLE
Add Pitagon Sans Text

### ISSUE THREAD

**Issue by travistran1989** [google/fonts#5978]
**Font Project Git Repo URL:**
https://github.com/ThePitagon/pitagon-sans-text

**Super short description of the Font Family:**
Pitagon Sans Text is a part of the Pitagon font set, which be used in Pi Design System.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

![image1](https://user-images.githubusercontent.com/4491627/223510014-fc4d2407-e28b-4635-8818-805a853e3a6c.png)

**Comment by kenmcd** [comment]
> Pitagon Sans Text is a part of the Pitagon font set, which be used in Pi Design System.

Could not find anything about this font set.
https://pitagon.vn/

**Comment by travistran1989** [comment]
For some reasons, our website doesn't use this font, because it may cause the website performance reduces. After publishing to Google Fonts, we will update the website then.
Currently, the font set is being used in our design system for our applications. We've received some partners' requests of using this font set, so we think we need to open source this font and publish to community.

**Comment by kenmcd** [comment]
> Currently, the font set is being used in our design system for our applications.

Since you mentioned the "Pitagon font set", I tried to find any information about the full font set by reviewing the online info about the design system - but found nothing.

**Comment by travistran1989** [comment]
> > Currently, the font set is being used in our design system for our applications.
> 
> Since you mentioned the "Pitagon font set", I tried to find any information about the full font set by reviewing the online info about the design system - but found nothing.
> 
> Note: you may want to mention that this is a variable font family. And the excellent language coverage. Both good things.

You couldn't find anything on the internet because we haven't made the design system public yet. We built the design system in Figma and applied to all of applications we created.

This is a screenshot of the design system:
![2023-03-08_11-36-13](https://user-images.githubusercontent.com/4491627/223621156-f42804bf-e72d-4f86-bd4a-c6e21bc20d0e.png)

Pitagon Sans Text is a variable font and I think it also have a excellent Latin language coverage. I also ran test and proof by using the command `make test` and `make proof` before creating this issue. The font set has about 1200 glyphs in normal style and the same in italic style.
![2023-03-08_11-43-54](https://user-images.githubusercontent.com/4491627/223621982-963d096c-a38d-4363-84e4-3ca9ee689b0d.png)

**Comment by travistran1989** [comment]
Hope the information I've provided above could help you decide easier. Thanks for your very quick response ^^

**Comment by RosaWagner** [comment]
Hi @travistran1989, thanks for your submission. 

All of this seems to be of very good quality! We have our quarterly review board this afternoon to accept/reject the submissions, so you'll have an answer pretty quickly.

I only quickly looked over the files and saw 2 things:
- Austral sign is not used since 1993 and Franc sign have never been used. If you want to reduce file size you can safely remove them.
- ogonek position can be adjusted on `e` and a bit on `o` (this is a good resource https://www.twardoch.com/download/polishhowto/ogonek.html)

Please be aware that if the family is added to the catalog, the API won't serve the stylistic sets (they will be only available in the downloadable zip file).

**Comment by travistran1989** [comment]
Hi @RosaWagner , thanks for your response.

The things you saw is pretty good for the font set's quality. I will update and release in the next version of the font set.
Hope to have good news from you.

Thanks a lot!

**Comment by travistran1989** [comment]
Also, I've just released another font in the Pitagon font set. I hope they will be published in this review, too.

**Comment by Cogli** [comment]
If I'm not mistaken, Pitagon sans, text and serif are all forks of fonts already enlisted in GF catalog, namely Maven Pro, Plus Jakarta Sans and Petrona. Changelog doesn't report much about modification, except for adding icon set. Maybe more emphasis on differences form those fonts would help users in choosing among them.

**Comment by RosaWagner** [comment]
@travistran1989 the submission review has been reported, so no answer yet.

As a side note following @Cogli's comment, I confirm that GF expects full transparency and precision in the README file about the open source fonts that were forked. For example if entire outlines were copied to then be modified. The README should be clear about what was taken, what remained and what changed.

As another side note, Futura is not an open source project ;)

**Comment by travistran1989** [comment]
Thank you @RosaWagner . I will ask our designers to detail the changes and update the README file.
Of course, Futura is not an open source project, so we didn't use any glyph from Futura. Futura inspires us ^^

**Comment by davelab6** [comment]
Thank you @RosaWagner, I agree with your comments. I will review with the GF leadership team and see if we can formalize the ethic you mention. We also have a different approach to icon sets, so this might be more appropriate to add these as icon fonts in future. 

@travistran1989 you said, 

> For some reasons, our website doesn't use this font, because it may cause the website performance reduces. After publishing to Google Fonts, we will update the website then.

I wonder if you might switch to the fonts in the GF API that your forks are based on :)

**Comment by travistran1989** [comment]
Hi @RosaWagner , @davelab6 ,
Sorry for my late reply.
I've had a busy few months so I can't give you an immediate update. We have updated the source font to the latest version, as well as updated the README according to the reference repository you sent. I also added a python script to create some images comparing the difference of characters between font sets.
Let me know if we need anything more. Wishing you a happy and productive new week.

**Comment by travistran1989** [comment]
Adding new font Pitagon Sans Mono to the font set.

https://github.com/google/fonts/issues/6606

**Comment by eliheuer** [comment]
> As a side note following @Cogli's comment, I confirm that GF expects full transparency and precision in the README file about the open source fonts that were forked. For example if entire outlines were copied to then be modified. The README should be clear about what was taken, what remained and what changed.

Pitagon Sans Mono has the same issue. It is a fork of Jet Brains Mono but makes no mention of that fact in the README, which was updated today. The README lists other fonts as inspiration, but not Jet Brains Mono, which I feel is very dishonest given that this issue was already raised with this previous fonts.

<img width="861" alt="Screenshot 2023-08-08 at 3 21 10 PM" src="https://github.com/google/fonts/assets/5162664/d4a7ad0a-673e-4507-a939-1110540f4517">

<img width="1919" alt="Screenshot 2023-08-08 at 3 23 55 PM" src="https://github.com/google/fonts/assets/5162664/ef14ebcd-2daa-4b80-b3b8-77d9c090b467">

Pitagon Sans Mono also has a [LOT of outline quality issues](https://github.com/google/fonts/issues/6606). In my opinion all Pitagon fonts should not be onboarded.

**Comment by travistran1989** [comment]
I understand the issue and we will improve our works. Thank you @eliheuer !
