### ISSUE TITLE
Add Pitagon Sans

### ISSUE THREAD

**Issue by travistran1989** [google/fonts#5979]
**Font Project Git Repo URL:**
https://github.com/ThePitagon/pitagon-sans

**Super short description of the Font Family:**
Pitagon Sans is a part of the Pitagon font set, which be used in Pi Design System.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

**Image:**

![image1](https://user-images.githubusercontent.com/4491627/223620095-1e1d45c6-d596-4b7b-bca7-22affd602872.png)

**Comment by RosaWagner** [comment]
Same comment as in https://github.com/google/fonts/issues/5978#issuecomment-1569770342

<img width="967" alt="Capture d’écran 2023-05-31 à 10 56 51" src="https://github.com/google/fonts/assets/12222436/431bae07-c6de-4c3d-b0cc-387617f0ffb6">
