### ISSUE TITLE
Update Tier 3 Noto Fonts (summary)

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#6176]
The Noto development focus for Q2 2023 is on Tier 3 fonts. You might think that after tier 1 we would move onto tier 2, but if you remove Myanmar (which just needs a complete redraw), Tier 2 only has a very small number of issues outstanding, whereas tier 3 has 150 issues, so that's the place to make an impact:

- [x] Noto Sans Symbols (#6461)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Symbols 2 (#6460)
	- [x] Development
	- [x] QA
	- [x] Release
- [ ] Noto Serif Tibetan (Ran out of time, did not happen)
	- [x] Development
	- [ ] QA
	- [ ] Release
- [x] ~Noto Sans Math~ *Recently released*
- [x] Noto Sans Siddham (#6399)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Syloti Nagri (#6432)
	- [x] Development
	- [x] QA
	- [x] Release
- [ ] ~Noto Sans Mongolian~ (Holding over to Q3 as a re-engineered version is expected soon)
- [x] Noto Sans SignWriting (#6456)
	- [x] Development
	- [x] QA
	- [x] Release
- [X] ~Noto Sans Syriac~ *Recently released*
- [ ] Noto Sans Syriac Western (Ran out of time, did not happen)
	- [ ] Development
	- [ ] QA
	- [ ] Release
- [x] Noto Sans Tifinagh (#6467)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Javanese (#6466)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Music (#6400)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Lao (#6412)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Lao Looped (#6414)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Serif Lao (#6411)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Modi (#6403)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans NKo (#6428 / #6429)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Sundanese (#6401)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] ~Noto Sans Tai Tham~ (Sadly this font has significant issues, and we need a re-draw.)
- [x] Noto Sans Gunjala Gondi (#6408)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Sharada (Waiting for re-draw, see #6017)
- [x] Noto Sans Tagalog (#6405)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Tai Viet (#6404)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Canadian Aboriginal (#6407)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Cham (#6458)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Coptic (#6431)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Hanifi Rohingya (#6430)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Hanunoo (#6418)
	- [x] Development
	- [x] QA
	- [x] Release
- [*] ~Noto Sans Multani~ - No updates needed!
- [x] Noto Sans Takri (#6409)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Sans Tangsa (#6410)
	- [x] Development
	- [x] QA
	- [x] Release
- [*] ~Noto Sans Thaana~ - No updates needed!
- [x] Noto Sans Zanabazar Square (#6413)
	- [x] Development
	- [x] QA
	- [x] Release
- [*] ~Noto Sans Bamum~ - No updates needed!
- [*] ~Noto Sans Duployan~ *Recently released*
- [x] Noto Sans Khojki (#6247)
	- [x] Development
	- [x] QA
	- [x] Release
- [x] Noto Serif Khojki (#6426)
	- [x] Development
	- [x] QA
	- [x] Release
- ~Noto Sans Meetei Mayek~  (No updates necessary)
- ~Noto Sans Miao~  (No updates necessary)
- ~Noto Sans NP Hmong~ (No updates necessary)
- ~Noto Sans Pahawh Hmong~ (No updates necessary)
- [x] Noto Sans Rejang (#6419)
	- [x] Development
	- [x] QA
	- [x] Release
- ~Noto Sans Saurashtra~ (No updates necessary)
- ~ Noto Sans Tai Le~ (No updates necessary)

**Comment by LaPingvino** [comment]
I think you need a Milestone to have the desired behavior? Either way it's a known issue: https://github.com/orgs/community/discussions/17308
