### ISSUE TITLE
Playwrite localized handwriting families

### ISSUE THREAD

**Issue by vv-monsalve** [google/fonts#6449]
**Font Project Git Repo URL:**

Currently private.

**Super short description of the Font Family:**

This would be the second family of the [handwriting fonts](https://github.com/google/fonts/issues/6097).

**Requirements:**

- [X] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository

## Batch 1 of prioritized Fonts to publish**

- [x] **Playwrite BR** (Playwrite Brasil) #7646
- [x] **Playwrite CO** (Playwrite Colombia) #7669
- [x] **Playwrite DE GRU** (Playwrite Deutschland Grundschrift) #7647 
- [x] **Playwrite DE LA** (Playwrite Deutschland Lateinische Ausgangsschrift) #7708 
- [x] **Playwrite DE SAS** (Playwrite Deutschland Schulausgangschrift) #7709 
- [x] **Playwrite DE VA** (Playwrite Deutschland Vereinfachte Ausgangsschrift) #7710 
- [x] **Playwrite ES** (Playwrite España) #7714 
- [x] **Playwrite ES Deco** (Playwrite España Decorativa) #7713 
- [x] **Playwrite FR Moderne** (Playwrite France Moderne) #7715 
- [x] **Playwrite FR Trad** (Playwrite France Traditionnelle) #7670 
- [x] **Playwrite GB S** (Playwrite England SemiJoined) #7643
- [x] **Playwrite GB J** (Playwrite England Joined) #7716 
- [x] **Playwrite ID** (Playwrite Indonesia) #7720 
- [x] **Playwrite IN** (Playwrite India) #7722 
- [x] **Playwrite IT** Moderna (Playwrite Italia Moderna) #7724 
- [x] **Playwrite IT Trad** (Playwrite Italia Tradizionale) #7725 
- [x] **Playwrite MX** (Playwrite México) #7726 
- [x] **Playwrite NG** Modern (Playwrite Nigeria Modern) #7727 
- [x] **Playwrite TZ** (Playwrite Tanzania) #7736 
- [x] **Playwrite US** Modern (Playwrite USA Modern) #7737 
- [x] **Playwrite US Trad** (Playwrite USA Traditional) #7738
- [x] **Playwrite VN** (Playwrite Việt Nam) #7668 
- [x] **Playwrite ZA** (Playwrite South Africa) #7739 

## Batch 2 of Fonts to publish**

- [x] **Playwrite AR** (Playwrite Argentina) #7695 
- [x] **Playwrite AT** (Playwrite Österreich) #7696 
- [x] **Playwrite AU NSW** (Playwrite Australia NSW) #7697  
- [x] **Playwrite AU QLD** (Playwrite Australia QLD) #7698  
- [x] **Playwrite AU SA** (Playwrite Astralia SA) #7699  
- [x] **Playwrite AU TAS** (Playwrite Australia Tasmania) #7700  
- [x] **Playwrite AU VIC** (Playwrite Australia Victoria) #7701 
- [x] **Playwrite BE VLG** (Playwrite België Vlaams Gewest) #7702  
- [x] **Playwrite BE WAL** (Playwrite België Walloon) #7703 
- [x] **Playwrite CA** (Playwrite Canada) #7704  
- [x] **Playwrite CL** (Playwrite Chile) #7705 
- [x] **Playwrite CU** (Playwrite Cuba) #7706  
- [x] **Playwrite CZ** (Playwrite Česko) #7707 
- [x] **Playwrite DK Loopet** (Playwrite Danmark Loopet) #7711 
- [x] **Playwrite DK Uloopet** (Playwrite Danmark Uloopet) #7712 
- [x] **Playwrite HR Lijeva** (Playwrite Hrvatska Lijeva) #7717  
- [x] **Playwrite HR** (Playwrite Hrvatska) #7718  
- [x] **Playwrite HU** Modern (Playwrite Magyarország) #7719  
- [x] **Playwrite IE** (Playwrite Ireland) #7721
- [x] **Playwrite IS** (Playwrite Ísland) #7723 
- [x] **Playwrite NL** (Playwrite Netherland) #7728
- [x] **Playwrite NO** (Playwrite Norge) #7729 
- [x] **Playwrite NZ** (Playwrite New Zealand) #7730
- [x] **Playwrite PE** (Playwrite Perú) #7731  
- [x] **Playwrite PL** (Playwrite Polska) #7732
- [x] **Playwrite PT** (Playwrite Portugal) #7733
- [x] **Playwrite RO** (Playwrite România) #7734
- [x] **Playwrite SK** (Playwrite Slovensko) #7735

**Comment by vv-monsalve** [comment]
Issues with feedback opened after the first FB round on all 43 models.

**Comment by chrissimpkins** [comment]
Edited title to Playpen Sans from Playpen.

**Comment by chrissimpkins** [comment]
Moved to Q4.  We plan to onboard Playpen Sans in Q3, not the localized Playpen families

**Comment by chrissimpkins** [comment]
The project name was changed to "Playwrite".  Updated the title

**Comment by vv-monsalve** [comment]
An extensive revision to the name schema is ongoing, 1considering nameID4 length limitations.
Kerning still needs to be added.

**Comment by vv-monsalve** [comment]
PRs for two test cases have been done this year. The last production/engineering stage will be done on 2024 Q1.

**Comment by chrissimpkins** [comment]
@vv-monsalve Will you please enumerate all of the planned localized versions here?  Then, let's open a new issue on the tracker for each since they will be onboarded separately.  Thanks!

**Comment by vv-monsalve** [comment]
After our last meeting, Tobias proposed publishing the font according to the country's population. So I'll add that data into our spreadsheets and then add a list ordered according to that here.

**Comment by vv-monsalve** [comment]
I've added the list of the first batch of fonts following the above prioritization.

**Comment by vv-monsalve** [comment]
Final steps in progress:

- [ ] Final kerning revision
- [ ] Finishing up display name decisions
- [ ] Articulated documentation pieces
- [ ] Build system migration

**Comment by vv-monsalve** [comment]
PRs for prioritized first Batch is in progress

**Comment by vv-monsalve** [comment]
We have more in the list, so reopening it :)

**Comment by emmamarichal** [comment]
@vv-monsalve it's automatically closed when I merge the PRs, should we stop linking them to that issue?

**Comment by vv-monsalve** [comment]
No, I think I'll keep opening it again as long as needed.

**Comment by vv-monsalve** [comment]
All the PRs for Playwrite project have been done now 🎉
