### ISSUE TITLE
Add VCR OSD Mono

### ISSUE THREAD

**Issue by MegaOmegaSanSUS** [google/fonts#6489]
**Font Project Git Repo URL:**

**Super short description of the Font Family:**

**Requirements:**

I understand that Google Fonts will publish only fonts that matches [its requirements](https://googlefonts.github.io/gf-guide/), and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [ ] Family name is unique according to namecheck.fontdata.com
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [ ] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [ ] I am the author of the font or the author agreed to this submission
- [ ] I will maintain the repository

**Image:**

![image](https://github.com/google/fonts/assets/93817630/9a089a4d-f066-48a6-943f-775cdcfb4a1b)

**Comment by inferno986return** [comment]
It would be cool to have this font included. Do you have a link to it?

**Comment by RosaWagner** [comment]
Hi @MegaOmegaSanSUS, thanks for your submission. Unfortunately this family doesn't match the Google Fonts requirements listed above, therefore it won't be onboarded.
