### ISSUE TITLE
Add A Letra Do Reino

### ISSUE THREAD

**Issue by DistritoXermar** [google/fonts#6601]
(https://aletradoreino.gal)

‘A Letra do Reino’ rescata e pon en valor a proposta tipográfica baseada en exemplos concretos da historia da nosa cultura escrita. Tipografía galega. Rescatar, documentar, catalogar e definir con criterios científicos un aspecto, o tipográfico, fundamental da nosa cultura, é o obxectivo inicial do proxecto.

Fonte de uso e descarga libre.

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [ ] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

Attach here a pic or a screenshot 
![a letra do reino 2](https://github.com/google/fonts/assets/141557068/a1a9b681-b156-4979-bbf8-4a71103ab52f)
of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by applecuckoo** [comment]
I can't speak for Google Fonts, but I can say for sure that there doesn't seem to be a Git repository or an OFL license. The Dropbox has the .vfb source file and .otf and .ttf builds. No need to worry, someone from Google Fonts will be able to give feedback.

**Comment by RosaWagner** [comment]
Hi @DistritoXermar, thanks for your submission. I could review the fontlab file downloadable from the website, this is an interesting project. 

Unfortunately the font is not in a state where we could onbaord it:
- There is no legal metadata inside the font at all, therefore we can't legally distribute it. We would need proper description of a license (preferably the OFL). More info here: https://googlefonts.github.io/gf-guide/license-file.html and here: https://googlefonts.github.io/gf-guide/requirements.html#font-copyright-and-license
- The glyphset is incomplete. More info here: https://googlefonts.github.io/gf-guide/requirements.html#glyph-sets
- The quality of the outlines could be improve. More info here: https://googlefonts.github.io/gf-guide/outlines.html

We would be happy to re-review this submission once these 3 points are solved :)

**Comment by RosaWagner** [comment]
Since there is no development on this project since last summer, I am closing this issue. @DistritoXermar please feel free to re-open an issue once the points mentioned above are fixed :)
