### ISSUE TITLE
Add VU Pro

### ISSUE THREAD

**Issue by Yash10102010** [google/fonts#6633]
**Font Project Git Repo URL:** https://github.com/Yash10102010/VU-Pro

**Super short description of the Font Family:** tall X-height, grotesque font.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:** 
![Screenshot 2023-08-20 142953](https://github.com/google/fonts/assets/142717887/f72aef05-6a8e-4102-a476-3077ed93510d)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by eliheuer** [comment]
@Yash10102010 Hello, thanks for the submission. I don't see source files, releases, or a license in the upstream repo. Please look at other Google Fonts project on GitHub for examples of what to do and update the VU-Pro Git repository if you want it to be considered for onboarding.

**Comment by Yash10102010** [comment]
here is the url https://github.com/Yash10102010/VU-Pro

**Comment by eliheuer** [comment]
@Yash10102010 Thanks! I don't see source files, releases, or a license in the upstream repo. You will need those before we can consider this.

Please see the Google Fonts documentation: https://googlefonts.github.io/gf-guide/

**Comment by RosaWagner** [comment]
It looks like a fork of Inter with some minor changes to few letters of the basic latin alphabet. It becomes obvious when looking at the entire glyphset. So I don't think we would onboarding it cause it doesn't bring much to the current library in addition to not be super honest about the design process.
