### ISSUE TITLE
Madinah-Font 

### ISSUE THREAD

**Issue by AnasAlhejaili** [google/fonts#6851]
**Font Project Git Repo URL:**
https://github.com/AnasAlhejaili/Madinah-Font

**Super short description of the Font Family:**
It represents a unique visual identity for Al-Madinah al-Munawwarah.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![57479900-e656-43f6-acff-a6cb1876e28a](https://github.com/google/fonts/assets/68231883/bc6ae56e-05d1-4859-91f6-444773fab7fa)

Attach here a pic or a screenshot 
[googlefont license 2.zip](https://github.com/google/fonts/files/12878736/googlefont.license.2.zip)
of the font. One image is enough, it can be a few letters, to give a quick overview

**Comment by eliheuer** [comment]
@AnasAlhejaili Thanks! I don't see a link to a Git repository, but the following are both selected:
- The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- The source files are available in the repository

Is there a public Git repository for this typeface?

**Comment by AnasAlhejaili** [comment]
> @AnasAlhejaili Thanks! I don't see a link to a Git repository, but the following are both selected:
> 
> * The repository respects the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
> * The source files are available in the repository
> 
> Is there a public Git repository for this typeface?

Sorry,
here is the repository link: https://github.com/AnasAlhejaili/Madinah-Font

**Comment by AnasAlhejaili** [comment]
@eliheuer I added the source

**Comment by RosaWagner** [comment]
Hi @AnasAlhejaili, the sources are still missing from the repository, and the license file is empty. Therefore we can't review.
I close this issue since there has been no development for a week, please feel free to re-open one when you think you matched the requirements listed above :)

 Note: the name conflicts with a commercial fonts: https://www.myfonts.com/collections/madinah-authentic-font-ergibi-studio.

**Comment by AnasAlhejaili** [comment]
updated the repository it should have all the necessary files now,
for the name if we change it to Madinah-City font will it still cause conflict? thanks

**Comment by AnasAlhejaili** [comment]
@RosaWagner I am not sure how to re-open the issue

**Comment by RosaWagner** [comment]
@AnasAlhejaili you can open a new issue. I am in a sabbatical and not contracted by Google anymore, no need to tag me I. The new one.

**Comment by AnasAlhejaili** [comment]
> @AnasAlhejaili you can open a new issue. I am in a sabbatical and not contracted by Google anymore, no need to tag me I. The new one.

sorry about that and thank you for your help and time.
