### ISSUE TITLE
Add Pixeltron

### ISSUE THREAD

**Issue by Server360** [google/fonts#6977]
**Font Project Git Repo URL:**
https://github.com/Server360/Pixeltron/tree/main

**Super short description of the Font Family:**
Pixeltron is a font inspired by highway signs, calculators, and horror games.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [ ] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [ ] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [ ] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [ ] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**
![pixeltron_example](https://github.com/google/fonts/assets/144066996/10087f71-db54-448f-a8ff-25c211f4df71)

Attach here a pic or a screenshot of the font. One image is enough, it can be a few letters, to give a quick overview.

**Comment by emmamarichal** [comment]
Hello @Server360, thank you for your submission. However, I don't see any source files in the repo (.ufo or .glyphs). We can't review the font without these files. 
Also, I see that the project is under the Apache2 license, and we currently accept projects under the OFL license.

Don't hesitate if you have any questions!

**Comment by RosaWagner** [comment]
I suggest we close that submission for these reasons:
- The license in the font metadata and the repo doesn't match
- The copyright holder doesn't match
- The glyphset is incomplete
- No source available 

@Server360 Please feel free to re-open a submission when the requirements listed above are actually fulfilled.
