### ISSUE TITLE
Add Edu SA Hand

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#7484]
**Font Project Git Repo URL:**

https://github.com/SorkinType/SASchoolHandAustralia

**Super short description of the Font Family:**

School handwriting models for South Australia.

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![shape](https://github.com/google/fonts/assets/106728/5541024d-8498-4e12-8549-91daf3b3efc1)

This family has multiple variant fonts associated with it. Please review the source font (first listed) first, and then the variants:

- [ ] Edu SA Hand #7405
- [ ] Edu SA Hand Arrows #7437
- [ ] Edu SA Hand Color
- [ ] Edu SA Hand Cursive #7438
- [ ] Edu SA Hand Dotted #7439
- [ ] Edu SA Hand Guidelines
- [ ] Edu SA Hand Outline #7440
- [ ] Edu SA Hand Precursive #7442
- [ ] Edu SA Hand Starters #7443
- [ ] Edu SA Arrows Guide #7434
- [ ] Edu SA Cursive Guide #7435
- [ ] Edu SA Dotted Guide #7436
- [ ] Edu SA Outline Guide #7444
- [ ] Edu SA Hand Pre Guide #7441
- [ ] Edu SA Starters Guide #7445

**Comment by vv-monsalve** [comment]
Many of the families of these Edu mega-families need a resolution on:

**Subset**
- Starters, Arrows, and Dotted variants only work on A--z and 0--9 letters (no accented letter, no punctuation marks). We have discussed some options for this case
    1. Publish the fonts as they are now.
        - Pro: Fonts can be merged now.
        - Con: It will be a buggy font, confusing users and weakening the project.
    2. Subsetting these variants to only include the working letters. 
        - Pro: It would deliver a clear message on the font support.
        - Con: That subset would be even smaller than Latin-Kernell. 
    3. Find a middle ground where the accented letter and punctuation marks receive the effect. 
        - Pro: It would be more useful, especially for teaching contexts where punctuation is relevant.
        - Con: It would require an added job from @EbenSorkin

**Handwriting names schema**
- We need to change the names here to fit our naming schema (Dots, Guides)

cc @davelab6 @chrissimpkins

**Comment by davelab6** [comment]
We discussed this in the gf contractor weekly standup just now and (i) was agreed to start

**Comment by vv-monsalve** [comment]
Edu VIC WA NT will be the benchmark mega-family. Next steps in https://github.com/google/fonts/issues/7485#issuecomment-2058951728
