### ISSUE TITLE
Add Edu VIC WA NT

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#7485]
**Font Project Git Repo URL:**

https://github.com/SorkinType/VICWANTSchoolhandAustralia

**Super short description of the Font Family:**

School handwriting models for Victoria, Western Australia and the Northern Territory

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![shape](https://github.com/google/fonts/assets/106728/3a8f6bb7-65c4-4bae-96f6-c33318a2d490)

This family has multiple variant fonts associated with it. Please review the *source font* (first listed) first, and then the variants:

- [x] Edu VIC WA NT Hand #7402
- [x] Edu VIC WA NT Arrows #7447
- [x] Edu VIC WA NT Cursive #7449
- [x] Edu VIC WA NT Dots #8020
- [x] Edu VIC WA NT Guide #8021
- [x] Edu VIC WA NT Pre #8022
- [ ] Edu VIC WA NT Outline #7455
- [ ] Edu VIC WA NT Starters #7458
- [ ] Edu VIC WA NT Arrows Guide #7446
- [ ] Edu VIC WA NT Cursive Guide #7448
- [ ] Edu VIC WA NT Dotted Guide #7450
- [ ] Edu VIC WA NT Outline Guide #7454
- [ ] Edu VIC WA NT Pre Guide #7456
- [ ] Edu VIC WA NT Starters Guide #7457

**Comment by simoncozens** [comment]
Summarizing various discussions about how to handle Edu Australia Hand fonts:

* We need to ensure path directions are corrected
* We need to make cursive forms correctly handle basic Latin accents
* Dots and "starter" variants, exceptionally, will be subsetted purely to a-zA-Z
* We will do this family (VIC WA NT) first and ensure we are happy with it before dealing with the others.

**Comment by vv-monsalve** [comment]
> * Outline, dots and "starter" variants, exceptionally, will be subsetted purely to a-zA-Z0-9

Plus Arrows?

**Comment by vv-monsalve** [comment]
- We agreed on the name standardization across handwriting families to keep library-wide consistency. So the Edu families will include:
    -  The `AU` two letters abbreviation for Australia in the font and file names
    - `Australia` in the display_name of these fonts (for how they will be presented in the Specimen)

**Comment by simoncozens** [comment]
All good from my side, over to @EbenSorkin because I found some joining issues.

**Comment by simoncozens** [comment]
I think subissues are a great idea for "superfamilies" like this!

**Comment by emmamarichal** [comment]
Yes indeed! I'm gonna replace the current to-do by sub issues and link each of them to the corresponding PR, to avoid to close this one each time a PR is merged. It will be also easier to track each family.

**Comment by emmamarichal** [comment]
@simoncozens, I listed all the related projects thanks to the sub-issues. Feel free to add comments/status directly there if needed!
All the closed issues are the merged (and not blocked) ones or already live.


You can easily see the corresponding PR by hovering over the small PR icon.


And this is the current state of the API, let me know if more issues need to be opened:

![Image](https://github.com/user-attachments/assets/bad3fd8a-3799-4163-93f1-5a5127b639c6)

**Comment by chrissimpkins** [comment]
Will the Edu projects in this issue & #7483 #7474 #7488 be ready to onboard in Q2?
