### ISSUE TITLE
Add Edu QLD

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#7487]
**Font Project Git Repo URL:**

https://github.com/SorkinType/QLDSchoolhandAustralia

**Super short description of the Font Family:**

School handwriting models for Queensland

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![shape](https://github.com/google/fonts/assets/106728/d10e9f94-d04e-42af-9762-9dbe87fb0f01)

This family has multiple variant fonts associated with it. Please review the *source font* (first listed) first, and then the variants:

- [ ] Edu QLD Hand #7404
- [ ] Edu QLD Hand Arrows #7424
- [ ] Edu QLD Hand Color
- [ ] Edu QLD Hand Cursive #7425
- [ ] Edu QLD Hand Dotted #7426
- [ ] Edu QLD Hand Starters #7431
- [ ] Edu QLD Hand Guidelines #7427
- [ ] Edu QLD Hand Outline #7248
- [ ] Edu QLD Hand Precursive #7430
- [ ] Edu QLD Arrows Guide #7421
- [ ] Edu QLD Cursive Guide #7422
- [ ] Edu QLD Dotted Guide #7423
- [ ] Edu QLD Hand Pre Guide #7429
- [ ] Edu QLD Outline Guide #7432
- [ ] Edu QLD Starters Guide #7433

**Comment by simoncozens** [comment]
I'm working on fixes to the cursive/semicursive for all of these fonts. Will send it back to you when these fixes are tested and PRed.
