### ISSUE TITLE
Add Edu NSW ACT

### ISSUE THREAD

**Issue by simoncozens** [google/fonts#7488]
**Font Project Git Repo URL:**

https://github.com/SorkinType/NSWACTSchoolhandAustralia

**Super short description of the Font Family:**

School handwriting models for New South Wales and the Australian Capital Territory

**Requirements:**

Google Fonts will publish only fonts that match its requirements. Please familiarize yourself with the complete documentation in the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) (GF-Guide) and ensure your font project complies with them before submitting the font family. You can also use the [Google Fonts Project Template](https://github.com/googlefonts/googlefonts-project-template), which will help you create a repository that follows the needed structure and includes build requirements.

By filling this issue, you can confirm the project meets the  requirements (by ticking the cases or putting x between the square brackets in text mode):

- [x] I read, agree, and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/index#pre-production-getting-your-fonts-ready-for-gf)
- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to [namecheck.fontdata.com](https://namecheck.fontdata.com/)
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I am the author of the font, or the author agreed to this submission
- [x] I will maintain the repository and participate in the onboarding process (addressing, solving, and responding to issues, merging pull requests, etc)

**Image:**

![shape](https://github.com/google/fonts/assets/106728/e061de0e-b686-4335-9bd0-594608f76738)

This family has multiple variant fonts associated with it. Please review the *source font* (first listed) first, and then the variants:

- [ ] Edu NSW ACT Hand #7403
- [ ] Edu NSW ACT Cursive #7410
- [ ] Edu NSW ACT Hand Arrows #7412
- [ ] Edu NSW ACT Hand Color
- [ ] Edu NSW ACT Hand Dotted #7413
- [ ] Edu NSW ACT Hand Pre #7415
- [ ] Edu NSW ACT Outline #7147
- [ ] Edu NSW ACT Starters #7420
- [ ] Edu NSW ACT Arrows Guide #7408
- [ ] Edu NSW ACT Cursive Guide #7409
- [ ] Edu NSW ACT Dotted Guide #7411
- [ ] Edu NSW ACT Hand Guide #7414
- [ ] Edu NSW ACT Outline Guide #7416
- [ ] Edu NSW ACT Pre Guide #7418
- [ ] Edu NSW ACT Starters Guide #7419

**Comment by vv-monsalve** [comment]
> - [ ] Edu NSW ACT Outline https://github.com/google/fonts/pull/7147

Bad link. I didn't find an open PR for this font, though.

**Comment by simoncozens** [comment]
Typo - I fixed it.
